//HintName: GenerateOnReadyAttribute.g.cs
// <auto-generated />
#if NETCOREAPP3_0_OR_GREATER
#nullable disable
#endif
using System;

namespace GodotAutoOnReady.Attributes
{
    [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
    internal class GenerateOnReadyAttribute : Attribute
    {
        internal readonly string InitMethodName;

        internal GenerateOnReadyAttribute(string initMethodName = "")
        {
            InitMethodName = initMethodName;
        }
    }
}