//HintName: GenerateReadyMethodAttribute.g.cs
// <auto-generated />
#nullable disable
using System;

namespace GodotAutoOnReady.SourceGenerators.Attributes
{
    [AttributeUsage(AttributeTargets.Class)]
    internal class GenerateReadyMethodAttribute : Attribute
    {
        internal readonly string InitMethodName;

        internal GenerateReadyMethodAttribute(string initMethodName = "")
        {
            InitMethodName = initMethodName;
        }
    }
}