//HintName: Sword.g.cs
// <auto-generated />
#nullable disable

using Godot;
using GodotAutoOnReady.SourceGenerators.Attributes;

public partial class Sword : Node
{
	private Sword()
	{
		Ready += {readySignalHandler};
	}

	private void bs6GM24mzVRFyLSxbW8Q_OnReady()
	{
		_Ready();
	}

	public override void _Ready()
	{
		Node = GetNode<DummyNode>("%SomeProp");
		Field = GetNode<DummyNode>("%SomeField");
	}
}
