//HintName: Sword.g.cs
// <auto-generated />
#nullable disable

using Godot;
using GodotAutoOnReady.SourceGenerators.Attributes;

namespace RPGGame
{
	public partial class Sword : Node
	{
		private Sword()
		{
			Ready += {readySignalHandler};
		}

		private void QgtmW2Wh7XaT0gPk0krW_OnReady()
		{
			_Ready();
		}

		public override void _Ready()
		{
			Node = GetNode<DummyNode>("%SomeProp");
			Field = GetNode<DummyNode>("%SomeField");
		}
	}
}
