//HintName: TestItem.g.cs
// <auto-generated />
#nullable disable

using Godot;
using GodotAutoOnReady.SourceGenerators.Attributes;

namespace GodotAutoOnReady.Console
{
	public partial class TestItem : BaseItem
	{
		private TestItem()
		{
			Ready += {readySignalHandler};
		}

		private void vQJxgs4vuE82uMP7CpUx_OnReady()
		{
			_Ready();
		}

		public override void _Ready()
		{
			Node = GetNode<DummyNode>("%path");
			Node2 = GetNode<DummyNode>("random path");
			Prop = GetNode<DummyNode>("cat");
			Field = GetNode<DummyNode>("cat field");
		}
	}
}
