//HintName: Sword.g.cs
// <auto-generated />

using Godot;
using GodotAutoOnReady.SourceGenerators.Attributes;

namespace RPGGame
{
	public partial class Sword : Node
	{
		private Sword()
		{
			Ready += RxBBvgfij8bp1ugUc3NG_OnReady;
		}

		private void RxBBvgfij8bp1ugUc3NG_OnReady()
		{
			_Ready();
		}

		public override void _Ready()
		{
			Node = GetNode<DummyNode>("%SomeProp");
			Field = GetNode<DummyNode>("%SomeField");
		}
	}
}
