//HintName: Sword.g.cs
// <auto-generated />
#nullable disable

using Godot;
using GodotAutoOnReady.Attributes;

namespace RPGGame
{
	public partial class Sword : Node
	{
		public void OnReadySetup()
		{
			Node = GetNode<DummyNode>("%SomeProp");
			Field = GetNode<DummyNode>("%SomeField");
		}
	}
}
