//HintName: OnReadyGetAttribute.g.cs
// <auto-generated />
#if NETCOREAPP3_0_OR_GREATER
#nullable disable
#endif
using System;

namespace GodotAutoOnReady.Attributes
{
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    internal class OnReadyGetAttribute : Attribute
    {
        internal readonly string Path;
        internal readonly bool OrNull;

        internal OnReadyGetAttribute(string path, bool orNull = false)
        {
            Path = path;
            OrNull = orNull;
        }
    }
}