using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("GodotAutoOnReady.Tests")]
namespace GodotAutoOnReady.SourceGenerator.Attributes;

internal static class GenerateOnReadyAttributeSource
{
    internal const string Name = "GenerateOnReadyAttribute";

    internal const string Source = """
    // <auto-generated />
    using System;

    #nullable disable

    namespace GodotAutoOnReady.Attributes
    {
        /// <summary>
        /// Every class that uses GetNode, GetRes or OnReady attributes has to be marked with GenerateOnReady,
        /// otherwise the source generator won't find it, and no source code will be generated.
        /// </summary>
        /// <remarks>
        /// When _Ready method is already declared or a default constructor exists, and a name for the custom setup method is not provided,
        /// the default name OnReadySetup is used.
        /// </remarks>
        [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        public sealed class GenerateOnReadyAttribute : Attribute
        {
            /// <value>
            /// Name used to generate custom setup method that can be called in _Ready.
            /// </value>
            public string SetupMethod { get; set; }
        }
    }
    """;
}
