//HintName: GetNodeAttribute.g.cs
// <auto-generated />
using System;

#nullable disable

namespace GodotAutoOnReady.Attributes
{
    /// <summary>
    /// Initializes a property or a field in the _Ready method or a custom setup method
    /// when _Ready can't be auto-generated.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    public sealed class GetNodeAttribute : Attribute
    {
        /// <value>
        /// Uses GetNodeOrNull instead of GetNode when assigning value to the property.
        /// </value>
        public bool OrNull { get; set; } = false;

        private string _path;

        /// <param name="path">Path to the node, when the path is empty a property name is used instead.</param>
        public GetNodeAttribute(string path = "")
        {
            _path = path;
        }
    }
}