//HintName: GetResAttribute.g.cs
// <auto-generated />
#if NETCOREAPP3_0_OR_GREATER
#nullable disable
#endif
using System;

namespace GodotAutoOnReady.Attributes
{
    /// <summary>
    /// Initializes a property or a field in the _Ready method or a custom setup method
    /// when _Ready can't be auto-generated.
    /// </summary>
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
    public sealed class GetResAttribute : Attribute
    {
        private readonly string _path;

        /// <param name="path">
        /// Full path to the resource.
        /// </param>
        public GetResAttribute(string path)
        {
            _path = path;
        }
    }
}