//HintName: Sword.g.cs
// <auto-generated />
#nullable disable

using Godot;
using GodotAutoOnReady.Attributes;

namespace RPGGame
{
	public partial class Sword : Node
	{
		public void Init()
		{
			Node = GetNode<DummyNode>("/root/Title");
			Field = GetNode<DummyNode>("/root/Titled");
		}
	}
}
