using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("GodotAutoOnReady.Tests")]
namespace GodotAutoOnReady.SourceGenerators.Attributes;

internal static class GenerateOnReadyAttributeSource
{
    internal const string Name = "GenerateOnReadyAttribute";

    internal const string Source = """
    // <auto-generated />
    #if NETCOREAPP3_0_OR_GREATER
    #nullable disable
    #endif
    using System;

    namespace GodotAutoOnReady.Attributes
    {
        /// <summary>
        /// Every class that uses GetNode, GetRes or OnReady attributes has to be marked with GenerateOnReady,
        /// otherwise the source generator won't find it, and no source code will be generated.
        /// </summary>
        /// <remarks>
        /// When _Ready method is already declared or a default constructor exists, and a name for the custom setup method is not provided,
        /// the default name OnReadySetup is used.
        /// </remarks>
        [AttributeUsage(AttributeTargets.Class, AllowMultiple = false, Inherited = false)]
        public sealed class GenerateOnReadyAttribute : Attribute
        {
            /// <summary>
            /// Name used to generate custom setup method that can be called in _Ready.
            /// </summary>
            public string SetupMethod { get; set; }
        }
    }
    """;
}
