namespace GodotAutoOnReady.SourceGenerators.Attributes;

internal static class GetNodeAttribute
{
    internal const string Name = "GetNode";

    internal const string Source = """
    // <auto-generated />
    #if NETCOREAPP3_0_OR_GREATER
    #nullable disable
    #endif
    using System;

    namespace GodotAutoOnReady.Attributes
    {
        /// <summary>
        /// Initializes a property or a field in the _Ready method or a custom setup method
        /// when _Ready can't be auto-generated.
        /// </summary>
        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
        internal class GetNodeAttribute : Attribute
        {
            /// <summary>
            /// Path to the node, when the path is empty a property name is used instead.
            /// </summary>
            internal string Path { get; set; }

            /// <summary>
            /// Uses GetNodeOrNull<T> instead of GetNode<T> when assigning value to this member.
            /// </summary>
            internal bool OrNull { get; set; } = false;
        }
    }
    """;
}
