namespace GodotAutoOnReady.SourceGenerators.Attributes;

internal static class GetResAttribute
{
    internal const string Name = "GetRes";

    internal const string Source = """
    // <auto-generated />
    #if NETCOREAPP3_0_OR_GREATER
    #nullable disable
    #endif
    using System;

    namespace GodotAutoOnReady.Attributes
    {
        /// <summary>
        /// Initializes a property or a field in the _Ready method or a custom setup method
        /// when _Ready can't be auto-generated.
        /// </summary>
        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
        internal class GetResAttribute : Attribute
        {
            private readonly string _path;
    
            /// <param name="path">
            /// Absolute path to the resource.
            /// </param>
            internal GetResAttribute(string path)
            {
                _path = path;
            }
        }
    }
    """;
}
