namespace GodotAutoOnReady.SourceGenerators.Attributes;

internal static class SourceOnReadyGetAttribute
{
    internal const string AttributeName = "OnReadyGet";
    internal const string Attribute = """
    // <auto-generated />
    #if NETCOREAPP3_0_OR_GREATER
    #nullable disable
    #endif
    using System;

    namespace GodotAutoOnReady.Attributes
    {
        [AttributeUsage(AttributeTargets.Property | AttributeTargets.Field, AllowMultiple = false, Inherited = false)]
        internal class OnReadyGetAttribute : Attribute
        {
            internal readonly string Path;
            internal bool OrNull { get; init; } = false;

            internal OnReadyGetAttribute(string path)
            {
                Path = path;
            }
        }
    }
    """;
}
