namespace GodotAutoOnReady.SourceGenerators.Attributes;

internal static class SourceOnReadyAttribute
{
    internal const string AttributeName = "OnReady";

    internal const string Attribute = """
    // <auto-generated />
    #if NETCOREAPP3_0_OR_GREATER
    #nullable disable
    #endif
    using System;

    /// <summary>
    /// Methods that accept 0 arguments and return void can be marked with this attribute.
    /// They will be called in _Ready or a custom setup method in the order they were declared and 
    /// after each member marked with GetNode or GetRes has been assigned. 
    /// <summary>
    namespace GodotAutoOnReady.Attributes
    {
        [AttributeUsage(AttributeTargets.Method, AllowMultiple = false, Inherited = false)]
        internal class OnReadyAttribute : Attribute
        {

        }
    }
    """;
}
